"use client"
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { useEffect } from 'react';
import { Inter, Sansita } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], weight: '700' })

const sansation = Sansita({ subsets: ['latin'], weight: '700' })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min")
  }, []);

  return (
    <html lang="en">
      <head>
        {/* <meta name="csrf-token" content="{{ csrf_token() }}" /> */}
        <title>phantom</title>
      </head>
      <body className={sansation.className}>{children}</body>
    </html>
  )
}
